// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
#nullable enable

using System.CodeDom.Compiler;

namespace LogOtter.JsonHal;

[GeneratedCode("Powershell Script", "1.0.0")]
public static class JsonHalLinkCollectionExtensions
{
    public static JsonHalLink? GetSelfLink(this JsonHalLinkCollection collection)
    {
        return collection.GetLink("self");
    }
    
    public static string? GetSelfHref(this JsonHalLinkCollection collection)
    {
        return collection.GetLink("self")?.Href;
    }
    
    public static void AddSelfLink(this JsonHalLinkCollection collection, string href)
    {
        collection.AddLink("self", href);
    }

    public static JsonHalLink? GetFirstLink(this JsonHalLinkCollection collection)
    {
        return collection.GetLink("first");
    }
    
    public static string? GetFirstHref(this JsonHalLinkCollection collection)
    {
        return collection.GetLink("first")?.Href;
    }
    
    public static void AddFirstLink(this JsonHalLinkCollection collection, string href)
    {
        collection.AddLink("first", href);
    }

    public static JsonHalLink? GetPrevLink(this JsonHalLinkCollection collection)
    {
        return collection.GetLink("prev");
    }
    
    public static string? GetPrevHref(this JsonHalLinkCollection collection)
    {
        return collection.GetLink("prev")?.Href;
    }
    
    public static void AddPrevLink(this JsonHalLinkCollection collection, string href)
    {
        collection.AddLink("prev", href);
    }

    public static JsonHalLink? GetNextLink(this JsonHalLinkCollection collection)
    {
        return collection.GetLink("next");
    }
    
    public static string? GetNextHref(this JsonHalLinkCollection collection)
    {
        return collection.GetLink("next")?.Href;
    }
    
    public static void AddNextLink(this JsonHalLinkCollection collection, string href)
    {
        collection.AddLink("next", href);
    }

    public static JsonHalLink? GetLastLink(this JsonHalLinkCollection collection)
    {
        return collection.GetLink("last");
    }
    
    public static string? GetLastHref(this JsonHalLinkCollection collection)
    {
        return collection.GetLink("last")?.Href;
    }
    
    public static void AddLastLink(this JsonHalLinkCollection collection, string href)
    {
        collection.AddLink("last", href);
    }
}
