name: Commit

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
     
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build
        env:
          TEST_COSMOS_CONNECTION_STRING: ${{ secrets.TEST_COSMOS_CONNECTION_STRING }}

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: .NET Tests
          path: .test-results/*.trx
          reporter: dotnet-trx
      
      - name: Publish to container registry
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} > docker login ghcr.io -u AButler --password-stdin
          dotnet publish --os linux --arch x64 -p:PublishProfile=DefaultContainer -p:VersionPrefix="0.0.0" --version-suffix 'commit+${{ github.sha }}' -p:ContainerImageTag=commit.${{ github.sha }}
          docker image tag customer-api:commit.${{ github.sha }} ghcr.io/logotter/customer-api:commit.${{ github.sha }}
          docker image tag customer-api:commit.${{ github.sha }} ghcr.io/logotter/customer-api:latest
          docker image push --all-tags ghcr.io/logotter/customer-api