name: Commit

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build
        env:
          TEST_COSMOS_CONNECTION_STRING: ${{ secrets.TEST_COSMOS_CONNECTION_STRING }}

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: .NET Tests
          path: .test-results/*.trx
          reporter: dotnet-trx

  publish:
    name: Publish to Azure
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json

      - name: Generate variables
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: (customer-api) Build for docker image
        run: |
          dotnet publish --configuration Release -p:VersionPrefix="0.0.0" --version-suffix 'commit+${{ steps.vars.outputs.sha_short }}' --output bin/docker-publish
        working-directory: sample/CustomerApi

      - name: (customer-api) Generate metadata for Docker
        id: api-meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/logotter/customer-api
          labels: |
            org.opencontainers.image.title=Customer API
            org.opencontainers.image.description=Sample API showing how to use LogOtter

      - name: (customer-api) Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: sample/CustomerApi
          tags: ${{ steps.api-meta.outputs.tags }}
          labels: ${{ steps.api-meta.outputs.labels }}

      - name: (customer-worker) Build for docker image
        run: |
          dotnet publish --configuration Release -p:VersionPrefix="0.0.0" --version-suffix 'commit+${{ steps.vars.outputs.sha_short }}' --output bin/docker-publish
        working-directory: sample/CustomerWorker

      - name: (customer-worker) Generate metadata for Docker
        id: worker-meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/logotter/customer-worker
          labels: |
            org.opencontainers.image.title=Customer Worker
            org.opencontainers.image.description=Sample worker showing how to use LogOtter

      - name: (customer-worker) Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: sample/CustomerWorker
          tags: ${{ steps.worker-meta.outputs.tags }}
          labels: ${{ steps.worker-meta.outputs.labels }}
