name: Deploy

concurrency:
  group: terraform
  cancel-in-progress: false

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      ARM_ACCESS_KEY:
        required: true
      AZURERM_CLIENT_ID:
        required: true
      AZURERM_CLIENT_SECRET:
        required: true
      AZURERM_SUBSCRIPTION_ID:
        required: true
      AZURERM_TENANT_ID:
        required: true
      DOCKER_REGISTRY_PASSWORD:
        required: true

jobs:
  publish:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -no-color -input=false
        working-directory: sample/terraform
        env:
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}

      - name: Terraform Plan
        run: terraform plan -out tfplan -var="docker_registry_password=${{ secrets.DOCKER_REGISTRY_PASSWORD }}" -var="container_tag_name=${{ inputs.version }}" -no-color -input=false
        working-directory: sample/terraform
        env:
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
          ARM_CLIENT_ID: ${{ secrets.AZURERM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURERM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURERM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURERM_TENANT_ID }}

      - name: Terraform Apply
        run: terraform apply -input=false -no-color tfplan
        working-directory: sample/terraform
        env:
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
          ARM_CLIENT_ID: ${{ secrets.AZURERM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURERM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURERM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURERM_TENANT_ID }}
