name: Terraform on Pull Request

concurrency:
  group: terraform
  cancel-in-progress: false

on:
  pull_request:
    branches: ["main"]
    paths:
      - sample/terraform/**

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: Check Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check -no-color
        continue-on-error: true
        working-directory: sample/terraform

      - name: Terraform Init
        id: init
        run: terraform init -no-color -input=false
        working-directory: sample/terraform
        env:
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: sample/terraform
        env:
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}

      - name: Terraform Plan
        id: plan
        run: terraform plan -var="azurerm_client_secret=${{ secrets.AZURERM_CLIENT_SECRET }}" -var="docker_registry_password=${{ secrets.DOCKER_REGISTRY_PASSWORD }}" -var="container_tag_name=${{ inputs.version }}" -no-color -input=false
        working-directory: sample/terraform
        env:
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}

      - name: Create PR comment
        uses: actions/github-script@v6
        env:
          VALIDATE_OUTPUT: '${{ steps.validate.outputs.stdout }}'
          PLAN_OUTPUT: '${{ steps.plan.outputs.stdout }}'
        with:
          script: |
            const script = require('./build/Create-TerraformPullRequestComment.js');
            const outcome = {
              fmt: '${{ steps.fmt.outcome }}' === 'success',
              init: '${{ steps.init.outcome }}' === 'success',
              validate: '${{ steps.validate.outcome }}' === 'success',
              plan: '${{ steps.plan.outcome }}' === 'success'
            };
            script({github, context, outcome});
