name: Pull Request

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    uses: ./.github/workflows/build-test.yml
    permissions:
      id-token: write
      contents: read
      checks: write
    secrets: inherit
