name: Publish Docker Images

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  publish-customer-api:
    uses: ./.github/workflows/publish-docker-image.yml
    permissions:
      contents: read
      packages: write
    with:
      project_name: customer-api
      project_title: Customer API
      project_description: Sample API showing how to use LogOtter
      project_path: sample/CustomerApi
      version: ${{ inputs.version }}
    secrets: inherit

  publish-customer-worker:
    uses: ./.github/workflows/publish-docker-image.yml
    permissions:
      contents: read
      packages: write
    with:
      project_name: customer-worker
      project_title: Customer Worker
      project_description: Sample Worker showing how to use LogOtter
      project_path: sample/CustomerWorker
      version: ${{ inputs.version }}
    secrets: inherit

  publish-hub:
    uses: ./.github/workflows/publish-docker-image.yml
    permissions:
      contents: read
      packages: write
    with:
      project_name: hub
      project_title: LogOtter Hub
      project_description: Hub combining event streams from multiple LogOtter services
      project_path: src/LogOtter.Hub
      version: ${{ inputs.version }}
    secrets: inherit
