name: Build Docker Image

on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string
      project_title:
        required: true
        type: string
      project_description:
        required: true
        type: string
      project_path:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  build:
    name: (${{ inputs.project_name }}) Publish Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json

      - name: Generate variables
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Login to the Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: (${{ inputs.project_name }}) Publish docker image
        run: |
          dotnet publish -t:PublishContainer -p:VersionPrefix="${{ inputs.version }}" -p:InformationalVersion="${{ inputs.version }}+${{ steps.vars.outputs.sha_short }}" -p:ContainerImageTag="${{ inputs.version }}" -p:ContainerRegistry="ghcr.io"
        working-directory: ${{ inputs.project_path }}
