name: Publish Docker Images

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  publish-customer-api:
    name: Publish Customer API
    uses: ./.github/workflows/publish-docker-image.yml
    permissions:
      contents: read
      packages: write
    with:
      project_path: sample/CustomerApi
      version: ${{ inputs.version }}
    secrets: inherit

  publish-customer-worker:
    name: Publish Customer Worker
    uses: ./.github/workflows/publish-docker-image.yml
    permissions:
      contents: read
      packages: write
    with:
      project_path: sample/CustomerWorker
      version: ${{ inputs.version }}
    secrets: inherit

  publish-hub:
    name: Publish Hub
    uses: ./.github/workflows/publish-docker-image.yml
    permissions:
      contents: read
      packages: write
    with:
      project_path: src/LogOtter.Hub
      version: ${{ inputs.version }}
    secrets: inherit
