name: Build Docker Image

on:
  workflow_call:
    inputs:
      project_path:
        required: true
        type: string
      project_name:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  build:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to the Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/logotter/${{ inputs.project_name }}:${{ inputs.version }}
          context: ${{ inputs.project_path }}
