name: Release

on:
  release:
    types: ["published"]

jobs:
  build:
    name: Build & Test
    uses: ./.github/workflows/build-test.yml
    permissions:
      id-token: write
      contents: read
      checks: write
    secrets: inherit

  release:
    name: Publish release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json

      - name: Parse version
        id: version
        run: .\build\Get-Version.ps1 -Ref "${env:GITHUB_REF}"
        shell: pwsh

      - name: Restore dependencies
        run: dotnet restore

      - name: Pack
        run: dotnet pack -p:VersionPrefix="${{ env.version_3 }}" --version-suffix "${{ env.version_suffix }}"

      - name: Publish
        run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.NUGET_APIKEY }} --source https://api.nuget.org/v3/index.json
        working-directory: .nupkgs

      - name: Upload artifact to action
        uses: actions/upload-artifact@v3
        with:
          name: nupkgs
          path: .nupkgs/

      - name: Upload artifacts to release
        uses: AButler/upload-release-assets@v3.0
        with:
          files: ".nupkgs/*.nupkg"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
